# Generated by Django 4.0.4 on 2022-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebase',
            name='last_scan',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
