# Generated by Django 4.0.4 on 2022-07-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codebase_last_scan'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='codebase',
            index=models.Index(fields=['content_type', 'object_id'], name='users_codeb_content_468d84_idx'),
        ),
    ]
