# Generated by Django 4.0.4 on 2022-07-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0003_codebase_users_codeb_content_468d84_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebase',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
