# Generated by Django 4.0.4 on 2022-05-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255, null=True, unique=True)),
                ('course_title', models.CharField(max_length=255, null=True, unique=True)),
                ('course_faculty', models.CharField(max_length=255, null=True)),
                ('course_department', models.CharField(max_length=255, null=True)),
                ('credit_unit', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('course_code',),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(default='+234', unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('matric_number', models.CharField(default='NAUB/', max_length=22, unique=True)),
                ('faculty', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('session', models.CharField(max_length=9, null=True)),
                ('level', models.TextField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=10, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=20, null=True)),
                ('lga', models.CharField(blank=True, max_length=50, null=True)),
                ('resident_address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('is_flaged', models.CharField(default=None, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='StudentProfile', to='students.course')),
            ],
            options={
                'ordering': ('matric_number',),
            },
        ),
        migrations.CreateModel(
            name='ScanRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='T.Y Buratai Gate', max_length=50, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='students.studentprofile')),
            ],
            options={
                'ordering': ('scan_time',),
            },
        ),
    ]
