# Generated by Django 4.0.4 on 2022-06-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='StudentProfile', to='students.course'),
        ),
    ]
