# Generated by Django 4.0.4 on 2022-09-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_delete_course_alter_studentprofile_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
